-- =============================================================================
-- MKD V2 - MODELO DE DADOS SIMPLIFICADO
-- =============================================================================
-- IMPORTANTE:
-- 1. Execute somente em um projeto Supabase novo e vazio.
-- 2. Todos os identificadores PascalCase precisam permanecer entre aspas.
-- 3. IDs do domínio são integer; somente o vínculo com auth.users usa UUID.
-- =============================================================================

begin;

create extension if not exists citext;

-- =============================================================================
-- TIPOS DO DOMÍNIO
-- =============================================================================

create type public."Ministerio" as enum (
  'Louvor',
  'Danca',
  'Midia',
  'Obreiros',
  'Celula'
);

create type public."PapelEquipe" as enum (
  'Lider',
  'Auxiliar',
  'Membro'
);

create type public."StatusEscala" as enum (
  'Rascunho',
  'Publicada',
  'Concluida',
  'Cancelada'
);

create type public."StatusConfirmacao" as enum (
  'Pendente',
  'Confirmada',
  'Recusada'
);

create type public."TipoNotificacao" as enum (
  'EscalaCriada',
  'EscalaAtualizada',
  'EscalaPublicada',
  'EscalaExcluida',
  'PessoaEscalada',
  'Informacao'
);

-- =============================================================================
-- 1. USUÁRIOS
-- Substitui users_profile, profiles e user_profiles.
-- Acesso gerencial é explícito. Acesso ministerial é derivado de EquipeMembro.
-- =============================================================================

create table public."Usuario" (
  "Id" integer generated by default as identity primary key,
  "AuthId" uuid unique references auth.users(id) on delete cascade,
  "Nome" varchar(100) not null,
  "Sobrenome" varchar(150),
  "Email" citext not null unique,
  "Telefone" varchar(20),
  "Gerencial" boolean not null default false,
  "Ativo" boolean not null default true,
  "CriadoEm" timestamptz not null default now(),
  "AtualizadoEm" timestamptz not null default now(),
  constraint "CK_Usuario_Nome" check (length(trim("Nome")) >= 2),
  constraint "CK_Usuario_Email" check (position('@' in "Email"::text) > 1)
);

comment on table public."Usuario" is
  'Cadastro da pessoa no MKD. AuthId é o único UUID do domínio por integrar com Supabase Auth.';

-- =============================================================================
-- 2. EQUIPES
-- Também representa Células. Campos de encontro ficam preenchidos em Celula.
-- ConfiguracaoRodizio guarda somente regras variáveis e validadas do Louvor.
-- =============================================================================

create table public."Equipe" (
  "Id" integer generated by default as identity primary key,
  "Nome" varchar(120) not null,
  "Ministerio" public."Ministerio" not null,
  "Cor" varchar(20),
  "LocalEncontro" varchar(200),
  "DiaSemana" smallint,
  "HorarioEncontro" time,
  "Observacoes" text,
  "ConfiguracaoRodizio" jsonb not null default '{}'::jsonb,
  "Ativo" boolean not null default true,
  "CriadoEm" timestamptz not null default now(),
  "AtualizadoEm" timestamptz not null default now(),
  constraint "CK_Equipe_Nome" check (length(trim("Nome")) >= 2),
  constraint "CK_Equipe_DiaSemana" check (
    "DiaSemana" is null or "DiaSemana" between 0 and 6
  ),
  constraint "CK_Equipe_ConfiguracaoRodizio" check (
    jsonb_typeof("ConfiguracaoRodizio") = 'object'
  )
);

create unique index "UX_Equipe_Ministerio_Nome_Ativa"
  on public."Equipe" ("Ministerio", lower("Nome"))
  where "Ativo" = true;

comment on column public."Equipe"."DiaSemana" is
  '0=domingo, 1=segunda, 2=terça, 3=quarta, 4=quinta, 5=sexta, 6=sábado.';

comment on column public."Equipe"."ConfiguracaoRodizio" is
  'Configuração variável do rodízio. Não usar para dados relacionais ou campos comuns.';

-- =============================================================================
-- 3. FUNÇÕES MINISTERIAIS
-- =============================================================================

create table public."Funcao" (
  "Id" integer generated by default as identity primary key,
  "Ministerio" public."Ministerio" not null,
  "Nome" varchar(100) not null,
  "Ativo" boolean not null default true,
  "CriadoEm" timestamptz not null default now(),
  constraint "CK_Funcao_Nome" check (length(trim("Nome")) >= 2),
  constraint "UQ_Funcao_Ministerio_Nome" unique ("Ministerio", "Nome")
);

-- =============================================================================
-- 4. MEMBROS DAS EQUIPES
-- Liderança deixa de ser perfil duplicado e passa a ser um papel na equipe.
-- Configuracao guarda preferências variáveis de rodízio do membro.
-- =============================================================================

create table public."EquipeMembro" (
  "Id" integer generated by default as identity primary key,
  "EquipeId" integer not null
    references public."Equipe"("Id") on delete cascade,
  "UsuarioId" integer not null
    references public."Usuario"("Id") on delete restrict,
  "Papel" public."PapelEquipe" not null default 'Membro',
  "Configuracao" jsonb not null default '{}'::jsonb,
  "Ativo" boolean not null default true,
  "CriadoEm" timestamptz not null default now(),
  "AtualizadoEm" timestamptz not null default now(),
  constraint "UQ_EquipeMembro_Equipe_Usuario" unique ("EquipeId", "UsuarioId"),
  constraint "CK_EquipeMembro_Configuracao" check (
    jsonb_typeof("Configuracao") = 'object'
  )
);

comment on column public."EquipeMembro"."Configuracao" is
  'Preferências opcionais: limite mensal, função preferida e restrições do rodízio.';

create table public."EquipeMembroFuncao" (
  "Id" integer generated by default as identity primary key,
  "EquipeMembroId" integer not null
    references public."EquipeMembro"("Id") on delete cascade,
  "FuncaoId" integer not null
    references public."Funcao"("Id") on delete restrict,
  "CriadoEm" timestamptz not null default now(),
  constraint "UQ_EquipeMembroFuncao" unique ("EquipeMembroId", "FuncaoId")
);

-- =============================================================================
-- 5. ESCALAS
-- Reuniões de Célula também são escalas da equipe do tipo Celula.
-- =============================================================================

create table public."Escala" (
  "Id" integer generated by default as identity primary key,
  "EquipeId" integer not null
    references public."Equipe"("Id") on delete restrict,
  "Data" date not null,
  "HorarioInicio" time,
  "HorarioFim" time,
  "Titulo" varchar(160),
  "Local" varchar(200),
  "Observacoes" text,
  "Status" public."StatusEscala" not null default 'Rascunho',
  "CriadoPorId" integer
    references public."Usuario"("Id") on delete set null,
  "AtualizadoPorId" integer
    references public."Usuario"("Id") on delete set null,
  "CriadoEm" timestamptz not null default now(),
  "AtualizadoEm" timestamptz not null default now(),
  constraint "CK_Escala_Horario" check (
    "HorarioFim" is null
    or "HorarioInicio" is null
    or "HorarioFim" > "HorarioInicio"
  ),
  constraint "UQ_Escala_Equipe_Data_Horario"
    unique ("EquipeId", "Data", "HorarioInicio")
);

create table public."EscalaMembro" (
  "Id" integer generated by default as identity primary key,
  "EscalaId" integer not null
    references public."Escala"("Id") on delete cascade,
  "EquipeMembroId" integer not null
    references public."EquipeMembro"("Id") on delete restrict,
  "Confirmacao" public."StatusConfirmacao" not null default 'Pendente',
  "RespondidoEm" timestamptz,
  "Observacoes" text,
  "CriadoEm" timestamptz not null default now(),
  constraint "UQ_EscalaMembro" unique ("EscalaId", "EquipeMembroId")
);

create table public."EscalaMembroFuncao" (
  "Id" integer generated by default as identity primary key,
  "EscalaMembroId" integer not null
    references public."EscalaMembro"("Id") on delete cascade,
  "FuncaoId" integer not null
    references public."Funcao"("Id") on delete restrict,
  "CriadoEm" timestamptz not null default now(),
  constraint "UQ_EscalaMembroFuncao" unique ("EscalaMembroId", "FuncaoId")
);

-- =============================================================================
-- 6. REPERTÓRIO
-- =============================================================================

create table public."Musica" (
  "Id" integer generated by default as identity primary key,
  "Nome" varchar(180) not null,
  "Artista" varchar(180),
  "TomOriginal" varchar(10),
  "Bpm" smallint,
  "DuracaoSegundos" integer,
  "UrlReferencia" text,
  "CaminhoAudio" text,
  "Letra" text,
  "Cifra" text,
  "PossuiInstrumentosVirtuais" boolean not null default false,
  "Observacoes" text,
  "CriadoPorId" integer
    references public."Usuario"("Id") on delete set null,
  "Ativo" boolean not null default true,
  "CriadoEm" timestamptz not null default now(),
  "AtualizadoEm" timestamptz not null default now(),
  constraint "CK_Musica_Nome" check (length(trim("Nome")) >= 1),
  constraint "CK_Musica_Bpm" check ("Bpm" is null or "Bpm" between 20 and 400),
  constraint "CK_Musica_Duracao" check (
    "DuracaoSegundos" is null or "DuracaoSegundos" > 0
  )
);

create table public."EscalaMusica" (
  "Id" integer generated by default as identity primary key,
  "EscalaId" integer not null
    references public."Escala"("Id") on delete cascade,
  "MusicaId" integer not null
    references public."Musica"("Id") on delete restrict,
  "TomExecucao" varchar(10),
  "Ordem" smallint not null,
  "Observacoes" text,
  "CriadoEm" timestamptz not null default now(),
  constraint "CK_EscalaMusica_Ordem" check ("Ordem" >= 0),
  constraint "UQ_EscalaMusica_Musica" unique ("EscalaId", "MusicaId"),
  constraint "UQ_EscalaMusica_Ordem" unique ("EscalaId", "Ordem")
);

-- =============================================================================
-- 7. EQUIPES PADRÃO DO LOUVOR
-- As regras específicas de baixista/baterista deixam de exigir tabelas próprias.
-- =============================================================================

create table public."EquipePadrao" (
  "Id" integer generated by default as identity primary key,
  "EquipeId" integer not null
    references public."Equipe"("Id") on delete cascade,
  "Nome" varchar(100) not null,
  "Codigo" varchar(50) not null,
  "OrdemRodizio" smallint,
  "PrimeiroFimSemana" boolean not null default false,
  "AtivoNoRodizio" boolean not null default true,
  "Ativo" boolean not null default true,
  "CriadoEm" timestamptz not null default now(),
  "AtualizadoEm" timestamptz not null default now(),
  constraint "CK_EquipePadrao_Ordem" check (
    "OrdemRodizio" is null or "OrdemRodizio" >= 0
  ),
  constraint "UQ_EquipePadrao_Codigo" unique ("EquipeId", "Codigo"),
  constraint "UQ_EquipePadrao_Nome" unique ("EquipeId", "Nome")
);

create unique index "UX_EquipePadrao_PrimeiroFimSemana"
  on public."EquipePadrao" ("EquipeId")
  where "PrimeiroFimSemana" = true and "Ativo" = true;

create table public."EquipePadraoMembro" (
  "Id" integer generated by default as identity primary key,
  "EquipePadraoId" integer not null
    references public."EquipePadrao"("Id") on delete cascade,
  "EquipeMembroId" integer not null
    references public."EquipeMembro"("Id") on delete restrict,
  "FuncaoId" integer not null
    references public."Funcao"("Id") on delete restrict,
  "Ordem" smallint not null default 0,
  "CriadoEm" timestamptz not null default now(),
  constraint "CK_EquipePadraoMembro_Ordem" check ("Ordem" >= 0),
  constraint "UQ_EquipePadraoMembro"
    unique ("EquipePadraoId", "EquipeMembroId", "FuncaoId")
);

-- =============================================================================
-- 8. PRESENÇA
-- Usada inicialmente por encontros de Células, mas compatível com qualquer equipe.
-- =============================================================================

create table public."Presenca" (
  "Id" integer generated by default as identity primary key,
  "EscalaId" integer not null
    references public."Escala"("Id") on delete cascade,
  "EquipeMembroId" integer not null
    references public."EquipeMembro"("Id") on delete restrict,
  "Presente" boolean not null default false,
  "Observacoes" text,
  "RegistradoPorId" integer
    references public."Usuario"("Id") on delete set null,
  "RegistradoEm" timestamptz not null default now(),
  constraint "UQ_Presenca" unique ("EscalaId", "EquipeMembroId")
);

-- =============================================================================
-- 9. NOTIFICAÇÕES
-- Duas tabelas são mantidas porque uma notificação pode ter vários destinatários,
-- e leitura/dispensa são estados individuais.
-- =============================================================================

create table public."Notificacao" (
  "Id" integer generated by default as identity primary key,
  "Tipo" public."TipoNotificacao" not null,
  "Titulo" varchar(160) not null,
  "Mensagem" text not null,
  "Link" text,
  "EscalaId" integer
    references public."Escala"("Id") on delete set null,
  "EquipeId" integer
    references public."Equipe"("Id") on delete set null,
  "AtorId" integer
    references public."Usuario"("Id") on delete set null,
  "Metadados" jsonb not null default '{}'::jsonb,
  "CriadoEm" timestamptz not null default now(),
  constraint "CK_Notificacao_Metadados" check (
    jsonb_typeof("Metadados") = 'object'
  )
);

create table public."NotificacaoDestinatario" (
  "Id" integer generated by default as identity primary key,
  "NotificacaoId" integer not null
    references public."Notificacao"("Id") on delete cascade,
  "UsuarioId" integer not null
    references public."Usuario"("Id") on delete cascade,
  "LidaEm" timestamptz,
  "DispensadaEm" timestamptz,
  "CriadoEm" timestamptz not null default now(),
  constraint "UQ_NotificacaoDestinatario"
    unique ("NotificacaoId", "UsuarioId")
);

-- =============================================================================
-- 10. CONTEÚDO INSTITUCIONAL
-- Singleton intencional: um registro ativo para o site principal.
-- =============================================================================

create table public."ConteudoSite" (
  "Id" integer generated by default as identity primary key,
  "Conteudo" jsonb not null default '{}'::jsonb,
  "Publicado" boolean not null default true,
  "AtualizadoPorId" integer
    references public."Usuario"("Id") on delete set null,
  "AtualizadoEm" timestamptz not null default now(),
  constraint "CK_ConteudoSite_Unico" check ("Id" = 1),
  constraint "CK_ConteudoSite_Json" check (jsonb_typeof("Conteudo") = 'object')
);

-- =============================================================================
-- VALIDAÇÃO DAS RELAÇÕES ENTRE MINISTÉRIO, EQUIPE, MEMBRO E FUNÇÃO
-- FKs garantem existência; estes triggers garantem compatibilidade de domínio.
-- =============================================================================

create or replace function public."ValidarFuncaoDoMembro"()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  "MinisterioDaEquipe" public."Ministerio";
  "MinisterioDaFuncao" public."Ministerio";
begin
  select e."Ministerio"
    into "MinisterioDaEquipe"
  from public."EquipeMembro" em
  join public."Equipe" e on e."Id" = em."EquipeId"
  where em."Id" = new."EquipeMembroId";

  select f."Ministerio"
    into "MinisterioDaFuncao"
  from public."Funcao" f
  where f."Id" = new."FuncaoId";

  if "MinisterioDaEquipe" is distinct from "MinisterioDaFuncao" then
    raise exception 'A função não pertence ao ministério da equipe.';
  end if;

  return new;
end;
$$;

create trigger "TR_EquipeMembroFuncao_ValidarMinisterio"
before insert or update on public."EquipeMembroFuncao"
for each row execute function public."ValidarFuncaoDoMembro"();

create or replace function public."ValidarMembroDaEscala"()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  "EquipeDaEscalaId" integer;
  "EquipeDoMembroId" integer;
begin
  select "EquipeId"
    into "EquipeDaEscalaId"
  from public."Escala"
  where "Id" = new."EscalaId";

  select "EquipeId"
    into "EquipeDoMembroId"
  from public."EquipeMembro"
  where "Id" = new."EquipeMembroId"
    and "Ativo" = true;

  if "EquipeDaEscalaId" is distinct from "EquipeDoMembroId" then
    raise exception 'O membro não pertence à equipe desta escala.';
  end if;

  return new;
end;
$$;

create trigger "TR_EscalaMembro_ValidarEquipe"
before insert or update on public."EscalaMembro"
for each row execute function public."ValidarMembroDaEscala"();

create or replace function public."ValidarFuncaoDaEscala"()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  "MinisterioDaEscala" public."Ministerio";
  "MinisterioDaFuncao" public."Ministerio";
begin
  select e."Ministerio"
    into "MinisterioDaEscala"
  from public."EscalaMembro" esm
  join public."Escala" es on es."Id" = esm."EscalaId"
  join public."Equipe" e on e."Id" = es."EquipeId"
  where esm."Id" = new."EscalaMembroId";

  select "Ministerio"
    into "MinisterioDaFuncao"
  from public."Funcao"
  where "Id" = new."FuncaoId";

  if "MinisterioDaEscala" is distinct from "MinisterioDaFuncao" then
    raise exception 'A função não pertence ao ministério desta escala.';
  end if;

  return new;
end;
$$;

create trigger "TR_EscalaMembroFuncao_ValidarMinisterio"
before insert or update on public."EscalaMembroFuncao"
for each row execute function public."ValidarFuncaoDaEscala"();

create or replace function public."ValidarEquipePadrao"()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public."Equipe"
    where "Id" = new."EquipeId"
      and "Ministerio" = 'Louvor'
  ) then
    raise exception 'Equipe padrão somente pode pertencer ao ministério de Louvor.';
  end if;

  return new;
end;
$$;

create trigger "TR_EquipePadrao_ValidarLouvor"
before insert or update on public."EquipePadrao"
for each row execute function public."ValidarEquipePadrao"();

create or replace function public."ValidarMembroDaEquipePadrao"()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  "EquipePadraoEquipeId" integer;
  "MembroEquipeId" integer;
  "FuncaoMinisterio" public."Ministerio";
begin
  select "EquipeId"
    into "EquipePadraoEquipeId"
  from public."EquipePadrao"
  where "Id" = new."EquipePadraoId";

  select "EquipeId"
    into "MembroEquipeId"
  from public."EquipeMembro"
  where "Id" = new."EquipeMembroId"
    and "Ativo" = true;

  select "Ministerio"
    into "FuncaoMinisterio"
  from public."Funcao"
  where "Id" = new."FuncaoId";

  if "EquipePadraoEquipeId" is distinct from "MembroEquipeId" then
    raise exception 'O membro não pertence à equipe deste padrão.';
  end if;

  if "FuncaoMinisterio" is distinct from 'Louvor'::public."Ministerio" then
    raise exception 'A função da equipe padrão precisa ser do Louvor.';
  end if;

  return new;
end;
$$;

create trigger "TR_EquipePadraoMembro_ValidarRelacoes"
before insert or update on public."EquipePadraoMembro"
for each row execute function public."ValidarMembroDaEquipePadrao"();

create trigger "TR_Presenca_ValidarEquipe"
before insert or update on public."Presenca"
for each row execute function public."ValidarMembroDaEscala"();

-- =============================================================================
-- ÍNDICES PARA FKs, FILTROS E ORDENAÇÕES FREQUENTES
-- =============================================================================

create index "IX_Usuario_AuthId"
  on public."Usuario" ("AuthId");

create index "IX_EquipeMembro_Usuario_Ativo"
  on public."EquipeMembro" ("UsuarioId", "EquipeId")
  where "Ativo" = true;

create index "IX_EquipeMembroFuncao_FuncaoId"
  on public."EquipeMembroFuncao" ("FuncaoId");

create index "IX_Escala_Equipe_Data"
  on public."Escala" ("EquipeId", "Data" desc);

create index "IX_Escala_Data_Status"
  on public."Escala" ("Data", "Status");

create index "IX_EscalaMembro_EquipeMembro"
  on public."EscalaMembro" ("EquipeMembroId", "EscalaId");

create index "IX_EscalaMembroFuncao_FuncaoId"
  on public."EscalaMembroFuncao" ("FuncaoId");

create index "IX_Musica_Nome_Ativa"
  on public."Musica" (lower("Nome"))
  where "Ativo" = true;

create index "IX_EscalaMusica_MusicaId"
  on public."EscalaMusica" ("MusicaId");

create index "IX_EquipePadrao_Equipe_Ordem"
  on public."EquipePadrao" ("EquipeId", "OrdemRodizio")
  where "Ativo" = true and "AtivoNoRodizio" = true;

create index "IX_EquipePadraoMembro_Membro"
  on public."EquipePadraoMembro" ("EquipeMembroId");

create index "IX_Presenca_Membro"
  on public."Presenca" ("EquipeMembroId", "EscalaId");

create index "IX_Notificacao_CriadoEm"
  on public."Notificacao" ("CriadoEm" desc);

create index "IX_NotificacaoDestinatario_NaoLida"
  on public."NotificacaoDestinatario" ("UsuarioId", "CriadoEm" desc)
  where "LidaEm" is null and "DispensadaEm" is null;

-- =============================================================================
-- ATUALIZAÇÃO AUTOMÁTICA DE TIMESTAMPS
-- =============================================================================

create or replace function public."DefinirAtualizadoEm"()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new."AtualizadoEm" = now();
  return new;
end;
$$;

create trigger "TR_Usuario_AtualizadoEm"
before update on public."Usuario"
for each row execute function public."DefinirAtualizadoEm"();

create trigger "TR_Equipe_AtualizadoEm"
before update on public."Equipe"
for each row execute function public."DefinirAtualizadoEm"();

create trigger "TR_EquipeMembro_AtualizadoEm"
before update on public."EquipeMembro"
for each row execute function public."DefinirAtualizadoEm"();

create trigger "TR_Escala_AtualizadoEm"
before update on public."Escala"
for each row execute function public."DefinirAtualizadoEm"();

create trigger "TR_Musica_AtualizadoEm"
before update on public."Musica"
for each row execute function public."DefinirAtualizadoEm"();

create trigger "TR_EquipePadrao_AtualizadoEm"
before update on public."EquipePadrao"
for each row execute function public."DefinirAtualizadoEm"();

-- =============================================================================
-- HELPERS DE AUTORIZAÇÃO
-- =============================================================================

create or replace function public."UsuarioAtualId"()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select "Id"
  from public."Usuario"
  where "AuthId" = auth.uid()
    and "Ativo" = true
  limit 1;
$$;

create or replace function public."EhGerencial"()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((
    select "Gerencial"
    from public."Usuario"
    where "AuthId" = auth.uid()
      and "Ativo" = true
    limit 1
  ), false);
$$;

create or replace function public."ParticipaDaEquipe"("EquipeConsultadaId" integer)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public."EhGerencial"() or exists (
    select 1
    from public."EquipeMembro"
    where "EquipeId" = "EquipeConsultadaId"
      and "UsuarioId" = public."UsuarioAtualId"()
      and "Ativo" = true
  );
$$;

create or replace function public."PodeGerenciarEquipe"("EquipeConsultadaId" integer)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public."EhGerencial"() or exists (
    select 1
    from public."EquipeMembro"
    where "EquipeId" = "EquipeConsultadaId"
      and "UsuarioId" = public."UsuarioAtualId"()
      and "Papel" in ('Lider', 'Auxiliar')
      and "Ativo" = true
  );
$$;

revoke all on function public."UsuarioAtualId"() from public;
revoke all on function public."EhGerencial"() from public;
revoke all on function public."ParticipaDaEquipe"(integer) from public;
revoke all on function public."PodeGerenciarEquipe"(integer) from public;

grant execute on function public."UsuarioAtualId"() to authenticated;
grant execute on function public."EhGerencial"() to authenticated;
grant execute on function public."ParticipaDaEquipe"(integer) to authenticated;
grant execute on function public."PodeGerenciarEquipe"(integer) to authenticated;

-- =============================================================================
-- RLS INICIAL
-- Policies específicas adicionais devem acompanhar cada caso de uso da V2.
-- =============================================================================

alter table public."Usuario" enable row level security;
alter table public."Equipe" enable row level security;
alter table public."Funcao" enable row level security;
alter table public."EquipeMembro" enable row level security;
alter table public."EquipeMembroFuncao" enable row level security;
alter table public."Escala" enable row level security;
alter table public."EscalaMembro" enable row level security;
alter table public."EscalaMembroFuncao" enable row level security;
alter table public."Musica" enable row level security;
alter table public."EscalaMusica" enable row level security;
alter table public."EquipePadrao" enable row level security;
alter table public."EquipePadraoMembro" enable row level security;
alter table public."Presenca" enable row level security;
alter table public."Notificacao" enable row level security;
alter table public."NotificacaoDestinatario" enable row level security;
alter table public."ConteudoSite" enable row level security;

create policy "Usuario_Ler_Proprio_Ou_Gerencial"
on public."Usuario"
for select to authenticated
using (
  "Id" = (select public."UsuarioAtualId"())
  or (select public."EhGerencial"())
);

create policy "Equipe_Ler_Se_Participa"
on public."Equipe"
for select to authenticated
using ((select public."ParticipaDaEquipe"("Id")));

create policy "Funcao_Ler_Autenticado"
on public."Funcao"
for select to authenticated
using (true);

create policy "EquipeMembro_Ler_Equipe"
on public."EquipeMembro"
for select to authenticated
using ((select public."ParticipaDaEquipe"("EquipeId")));

create policy "EquipeMembroFuncao_Ler_Equipe"
on public."EquipeMembroFuncao"
for select to authenticated
using (
  exists (
    select 1
    from public."EquipeMembro" em
    where em."Id" = "EquipeMembroFuncao"."EquipeMembroId"
      and public."ParticipaDaEquipe"(em."EquipeId")
  )
);

create policy "Escala_Ler_Equipe"
on public."Escala"
for select to authenticated
using ((select public."ParticipaDaEquipe"("EquipeId")));

create policy "Escala_Criar_Equipe"
on public."Escala"
for insert to authenticated
with check ((select public."PodeGerenciarEquipe"("EquipeId")));

create policy "Escala_Atualizar_Equipe"
on public."Escala"
for update to authenticated
using ((select public."PodeGerenciarEquipe"("EquipeId")))
with check ((select public."PodeGerenciarEquipe"("EquipeId")));

create policy "Escala_Excluir_Gerencial"
on public."Escala"
for delete to authenticated
using ((select public."EhGerencial"()));

create policy "Musica_Ler_Louvor"
on public."Musica"
for select to authenticated
using (
  (select public."EhGerencial"())
  or exists (
    select 1
    from public."EquipeMembro" em
    join public."Equipe" e on e."Id" = em."EquipeId"
    where em."UsuarioId" = public."UsuarioAtualId"()
      and em."Ativo" = true
      and e."Ativo" = true
      and e."Ministerio" = 'Louvor'
  )
);

create policy "NotificacaoDestinatario_Ler_Propria"
on public."NotificacaoDestinatario"
for select to authenticated
using ("UsuarioId" = (select public."UsuarioAtualId"()));

create policy "NotificacaoDestinatario_Atualizar_Propria"
on public."NotificacaoDestinatario"
for update to authenticated
using ("UsuarioId" = (select public."UsuarioAtualId"()))
with check ("UsuarioId" = (select public."UsuarioAtualId"()));

create policy "ConteudoSite_Ler_Publicado"
on public."ConteudoSite"
for select to anon, authenticated
using ("Publicado" = true or auth.uid() is not null);

-- =============================================================================
-- GRANTS MÍNIMOS
-- O Data API precisa dos grants, mas a RLS continua decidindo quais linhas.
-- =============================================================================

grant usage on schema public to anon, authenticated;
grant select on public."ConteudoSite" to anon;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
